{{- $gatewayAPI := (index .Values._cluster "gateway-api") | default "false" }}
{{- $gateway := .Values._namespace.gateway | default "" }}
{{- $host := .Values._namespace.host }}
{{- $grafanaHost := printf "grafana.%s" (.Values.host | default $host) }}

{{- if and (eq $gatewayAPI "true") (ne $gateway "") }}
{{ include "cozy-lib.gateway.httpRoute" (dict "ctx" . "name" "grafana" "hostname" $grafanaHost "backendName" "grafana-service" "backendPort" 3000) }}
{{- end }}
