{{- $gatewayAPI := (index .Values._cluster "gateway-api") | default "false" }}
{{- $clusterIssuer := (index .Values._cluster "issuer-name") | default "letsencrypt-prod" }}
{{- $gateway := .Values._namespace.gateway | default "" }}
{{- $host := .Values._namespace.host }}
{{- $bucketHost := printf "%s.%s" .Values.bucketName $host }}

{{- $gatewayClassName := .Values._namespace.gateway | default "" }}

{{- if and (eq $gatewayAPI "true") (ne $gateway "") }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.bucketName }}-ui
  annotations:
    cert-manager.io/cluster-issuer: {{ $clusterIssuer }}
spec:
  gatewayClassName: {{ $gatewayClassName }}
  infrastructure:
    labels:
      cozystack.io/gateway: {{ $gateway }}
  listeners:
  - name: https
    protocol: HTTPS
    port: 443
    hostname: {{ $bucketHost | quote }}
    tls:
      mode: Terminate
      certificateRefs:
      - name: {{ .Values.bucketName }}-ui-gateway-tls
    allowedRoutes:
      namespaces:
        from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.bucketName }}-ui
spec:
  parentRefs:
  - name: {{ .Values.bucketName }}-ui
  hostnames:
  - {{ $bucketHost | quote }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: {{ .Values.bucketName }}-ui
      port: 8080
{{- end }}
