---
apiVersion: cozystack.io/v1alpha1
kind: PackageSource
metadata:
  name: cozystack.cozystack-gateway
spec:
  sourceRef:
    kind: OCIRepository
    name: cozystack-packages
    namespace: cozy-system
    path: /
  variants:
  - name: default
    dependsOn:
    - cozystack.networking
    - cozystack.cert-manager
    libraries:
      - name: cozy-lib
        path: library/cozy-lib
    components:
    - name: cozystack-gateway
      path: system/cozystack-gateway
      libraries: ["cozy-lib"]
      install:
        namespace: cozy-gateway
        releaseName: cozystack-gateway
