---
apiVersion: cozystack.io/v1alpha1
kind: PackageSource
metadata:
  name: cozystack.envoy-gateway
spec:
  sourceRef:
    kind: OCIRepository
    name: cozystack-packages
    namespace: cozy-system
    path: /
  variants:
  - name: default
    dependsOn:
    - cozystack.networking
    - cozystack.cert-manager
    components:
    - name: envoy-gateway
      path: system/envoy-gateway
      install:
        namespace: cozy-envoy-gateway
        releaseName: envoy-gateway
