{{- $solver := (index .Values._cluster "solver") | default "http01" }}
{{- $ingressEnabled := (index .Values._cluster "ingress-enabled") | default "true" }}
{{- $gatewayAPI := (index .Values._cluster "gateway-api") | default "false" }}
{{- $gateway := (index .Values._cluster "gateway") | default "" }}

{{- define "cert-manager-issuers.solvers" -}}
{{- $solver := index . 0 -}}
{{- $ingressEnabled := index . 1 -}}
{{- $gatewayAPI := index . 2 -}}
{{- $gateway := index . 3 }}
solvers:
{{- if eq $solver "dns01" }}
- dns01:
    cloudflare:
      apiTokenSecretRef:
        name: cloudflare-api-token-secret
        key: api-token
{{- else }}
{{- if eq $ingressEnabled "true" }}
- http01:
    ingress:
      class: nginx
{{- end }}
{{- if and (eq $gatewayAPI "true") (ne $gateway "") }}
- http01:
    gatewayHTTPRoute:
      parentRefs:
      - name: acme-challenge
        namespace: {{ $gateway }}
        kind: Gateway
{{- end }}
{{- end }}
{{- end -}}

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
{{ include "cert-manager-issuers.solvers" (list $solver $ingressEnabled $gatewayAPI $gateway) | indent 4 }}

---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-stage
spec:
  acme:
    privateKeySecretRef:
      name: letsencrypt-stage
    server: https://acme-staging-v02.api.letsencrypt.org/directory
{{ include "cert-manager-issuers.solvers" (list $solver $ingressEnabled $gatewayAPI $gateway) | indent 4 }}  

---  

apiVersion: cert-manager.io/v1  
kind: ClusterIssuer  
metadata:  
  name: selfsigned-cluster-issuer  
spec:  
  selfSigned: {}
