{{- $kubeRootCa := lookup "v1" "ConfigMap" "kube-system" "kube-root-ca.crt" }}
{{- $cozystackCm := lookup "v1" "ConfigMap" "cozy-system" "cozystack" }}
{{- $bundleName := .Values.bundles.system.variant }}
{{- $bundle := tpl (.Files.Get (printf "bundles/%s.yaml" $bundleName)) . | fromYaml }}
{{- /* Read root-host from ConfigMap if available, else use chart values */ -}}
{{- $rootHost := .Values.publishing.host -}}
{{- if and $cozystackCm $cozystackCm.data -}}
{{- $rootHost = default $rootHost (index $cozystackCm.data "root-host") -}}
{{- end -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: cozystack-values
  namespace: cozy-system
  labels:
    reconcile.fluxcd.io/watch: Enabled
type: Opaque
stringData:
  values.yaml: |
    global:
      clusterDomain: {{ .Values.networking.clusterDomain | quote }}
    _cluster:
      root-host: {{ $rootHost | quote }}
      bundle-name: {{ .Values.bundles.system.variant | quote }}
      solver: {{ .Values.publishing.certificates.solver | quote }}
      issuer-name: {{ .Values.publishing.certificates.issuerName | quote }}
      oidc-enabled: {{ .Values.authentication.oidc.enabled | quote }}
      oidc-insecure-skip-verify: {{ .Values.authentication.oidc.insecureSkipVerify | quote }}
      extra-keycloak-redirect-uri-for-dashboard: {{ index .Values.authentication.oidc.keycloakExtraRedirectUri | quote }}
      keycloak-internal-url: {{ .Values.authentication.oidc.keycloakInternalUrl | quote }}
      expose-services: {{ .Values.publishing.exposedServices | join "," | quote }}
      expose-ingress: {{ .Values.publishing.ingressName | quote }}
      expose-external-ips: {{ .Values.publishing.externalIPs | join "," | quote }}
      cluster-domain: {{ .Values.networking.clusterDomain | quote }}
      api-server-endpoint: {{ .Values.publishing.apiServerEndpoint | quote }}
      {{- with .Values.branding }}
      branding:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.scheduling }}
      scheduling:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      ingress-enabled: {{ .Values.gateway.ingress | quote }}
      gateway-api: {{ .Values.gateway.gatewayAPI | quote }}
      gateway: {{ .Values.gateway.gatewayClass | quote }}
      {{- with .Values.publishing.hostnames }}
      hostnames:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with $kubeRootCa.data }}
      kube-root-ca: {{ index . "ca.crt" | b64enc | quote }}
      {{- end }}
