{{- $gatewayAPI := (index .Values._cluster "gateway-api") | default "false" }}
{{- $host := index .Values._cluster "root-host" }}
{{- $hostnames := .Values._cluster.hostnames | default dict }}
{{- $exposeServices := splitList "," ((index .Values._cluster "expose-services") | default "") }}
{{- $gateway := ((.Values._namespace).gateway) | default (index .Values._cluster "gateway") | default "" }}
{{- $gatewayClassName := $gateway }}

{{- $apiHost := index $hostnames "api" | default (printf "api.%s" $host) }}

{{- if and (eq $gatewayAPI "true") (has "api" $exposeServices) }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: kubernetes-api
  namespace: default
spec:
  gatewayClassName: {{ $gatewayClassName }}
  {{- if $gateway }}
  infrastructure:
    labels:
      cozystack.io/gateway: {{ $gateway }}
  {{- end }}
  listeners:
  - name: tls-passthrough
    protocol: TLS
    port: 443
    hostname: {{ $apiHost | quote }}
    tls:
      mode: Passthrough
    allowedRoutes:
      namespaces:
        from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: TLSRoute
metadata:
  name: kubernetes-api
  namespace: default
spec:
  parentRefs:
  - name: kubernetes-api
    sectionName: tls-passthrough
  hostnames:
  - {{ $apiHost | quote }}
  rules:
  - backendRefs:
    - name: kubernetes
      port: 443
{{- end }}
