{{- $gatewayAPI := (index .Values._cluster "gateway-api") | default "false" }}
{{- $host := index .Values._cluster "root-host" }}
{{- $hostnames := .Values._cluster.hostnames | default dict }}
{{- $exposeServices := splitList "," ((index .Values._cluster "expose-services") | default "") }}
{{- $gateway := ((.Values._namespace).gateway) | default (index .Values._cluster "gateway") | default "" }}
{{- $gatewayClassName := $gateway }}

{{- $vmExportHost := index $hostnames "vm-exportproxy" | default (printf "vm-exportproxy.%s" $host) }}

{{- if and (eq $gatewayAPI "true") (has "vm-exportproxy" $exposeServices) }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: vm-exportproxy
spec:
  gatewayClassName: {{ $gatewayClassName }}
  {{- if $gateway }}
  infrastructure:
    labels:
      cozystack.io/gateway: {{ $gateway }}
  {{- end }}
  listeners:
  - name: tls-passthrough
    protocol: TLS
    port: 443
    hostname: {{ $vmExportHost | quote }}
    tls:
      mode: Passthrough
    allowedRoutes:
      namespaces:
        from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: TLSRoute
metadata:
  name: vm-exportproxy
spec:
  parentRefs:
  - name: vm-exportproxy
    sectionName: tls-passthrough
  hostnames:
  - {{ $vmExportHost | quote }}
  rules:
  - backendRefs:
    - name: vm-exportproxy
      port: 443
{{- end }}
