apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backups.cozystack.io:strategy-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: backups.cozystack.io:strategy-controller
subjects:
- kind: ServiceAccount
  name: backupstrategy-controller
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backups.cozystack.io:strategy-controller:velero-configmaps
  namespace: cozy-velero
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: backups.cozystack.io:strategy-controller:velero-configmaps
subjects:
- kind: ServiceAccount
  name: backupstrategy-controller
  namespace: {{ .Release.Namespace }}
